### PR TITLE
cn

### PR DESCRIPTION
**Pull request by gracetong0630**

### CODE REVIEW

**Comment by gracetong0630** [comment]
update

**Comment by timlah** [comment]
I Added a couple lines that could use translating, fixed markup errors and renamed cn to zh (http://www.loc.gov/standards/iso639-2/php/code_list.php). We could also use zn-CN or zn-Hans to implicate that it's simplified Chinese, do you want that or is just "zh" okay? 

Also, if you could translate lines 7 and 92-9, that would be great. I added them yesterday for our exchanges section.

**Comment by gracetong0630** [comment]
Hello Tim

I will translate line 7 and 92-9. ZH is fine. thanks! :)


Best,
Grace

**Comment by timlah** [comment]
Hi, I edited my message afterwards, not sure if it got through to your email. lines 93-95 are part of the new content as well. Thank you for your time!

**Comment by gracetong0630** [comment]
Sure happy to do it tomorrow! Thank you 😊

**Comment by gracetong0630** [comment]
I updated the translation.:)

**Comment by gracetong0630** [comment]
Thank you so much Tim.:)

**Pull request merged**
